language: java
sudo: required

services:
- docker

jdk:
- openjdk8

branches:
  only:
  - master

cache:
  directories:
  - $HOME/google-cloud-sdk
  - $HOME/.m2

before_install:
- export CLOUDSDK_CORE_DISABLE_PROMPTS=1
- openssl aes-256-cbc -K $encrypted_3cc93b35c21b_key -iv $encrypted_3cc93b35c21b_iv -in travis-ci-petclinic.json.enc -out travis-ci-petclinic.json -d
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then
    rm -rf $HOME/google-cloud-sdk;
    curl https://sdk.cloud.google.com | bash;
  fi
- source $HOME/google-cloud-sdk/path.bash.inc
- gcloud auth activate-service-account --key-file=$TRAVIS_BUILD_DIR/travis-ci-petclinic.json
- gcloud config set core/project $PROJECT_ID
- gcloud components install beta kubectl
- export DOCKER_GOOGLE_CREDENTIALS=$TRAVIS_BUILD_DIR/travis-ci-petclinic.json

jobs:
  include:
  - stage: Build
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - ./mvnw install -PbuildDocker
  - stage: Deploy
    script:
    - gcloud beta container clusters get-credentials petclinic-cluster --region=us-central1
    - kubectl get pods
