spring:
  sleuth:
    sampler:
      probability: 1.0
    web:
      additional-skip-pattern: /actuator/.*
  cloud:
    gcp:
      spanner:
        instance-id: petclinic
        database: petclinic
      logging:
        trace-id-extractor: ZIPKIN
server:
  servlet:
    context-path: /api/vet
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"
