spring:
  sleuth:
    sampler:
      probability: 1.0
zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    vets-service: /vet/**
    visits-service: /visit/**
    customers-service: /customer/**
    api-gateway: /gateway/**
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      percentiles-histogram[http.server.requests]: true
      sla:
        http:
          server:
            requests: 1ms, 5ms
