spring:
  sleuth:
    sampler:
      probability: 1.0
    web:
      additional-skip-pattern: /actuator/.*
  cloud:
    gcp:
      logging:
        trace-id-extractor: ZIPKIN
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"
