spring:
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    gcp:
      spanner:
        instance-id: petclinic
        database: petclinic
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      percentiles-histogram[http.server.requests]: true
      sla:
        http:
          server:
            requests: 1ms, 5ms